configName: glcd_rgba8888_mxt_mzda_intddr_sk_freertos_wvga
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: PIC32MZ2064DAR169
projectName: ''
settings:
  PackageFilter: bsp;core;csp;gfx;quick_docs;touch;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-DA_DFP\1.3.111\atdf\PIC32MZ2064DAR169.atdf
