files:
- generatedChecksum: null
  logicalPath: ''
  name: app_glcd.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 3E90A7268114D314B037DE660DB74C27
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3E90A7268114D314B037DE660DB74C27
- generatedChecksum: FE58B06A9B638F2C7A17D3CE8FA7A776
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\gfx\driver\glcd
  name: drv_gfx_glcd.c
  physicalPath: gfx\driver\controller\glcd
  security: NON_SECURE
  type: SOURCE
  userChecksum: FE58B06A9B638F2C7A17D3CE8FA7A776
- generatedChecksum: 13F062B063A4F4AE0B19CE872943995B
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\driver\i2c
  name: drv_i2c.c
  physicalPath: driver\i2c\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 13F062B063A4F4AE0B19CE872943995B
- generatedChecksum: 37780F17759DED907A0F36E28BFB3136
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\driver\i2c
  name: drv_i2c_local.h
  physicalPath: driver\i2c\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 37780F17759DED907A0F36E28BFB3136
- generatedChecksum: D60987ADDBC55D814DF1F8934395B71C
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\driver\input
  name: drv_maxtouch.c
  physicalPath: driver\input
  security: NON_SECURE
  type: SOURCE
  userChecksum: D60987ADDBC55D814DF1F8934395B71C
- generatedChecksum: 4238740A6A08738E296E6139E26E53D8
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4238740A6A08738E296E6139E26E53D8
- generatedChecksum: 36FA79243A4ABD63DAAEA023290EDE3B
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\gfx\driver\glcd
  name: gfx_driver.c
  physicalPath: gfx\driver
  security: NON_SECURE
  type: SOURCE
  userChecksum: 36FA79243A4ABD63DAAEA023290EDE3B
- generatedChecksum: 4714D0CE8E5487A403A78DFA2DDC64B3
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4714D0CE8E5487A403A78DFA2DDC64B3
- generatedChecksum: 3371AE63D882C1CFA84725D76803B727
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3371AE63D882C1CFA84725D76803B727
- generatedChecksum: 9542827A9CCC1BBB58C8119CD906FB1E
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\gfx\driver\2dgpu
  name: libnano2d.c
  physicalPath: gfx\driver\processor\2dgpu
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9542827A9CCC1BBB58C8119CD906FB1E
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 8F9739C5D0D0813AB30AAD000A5CC9BC
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8F9739C5D0D0813AB30AAD000A5CC9BC
- generatedChecksum: 2FEFEA0D4E94F5A5F3D76BAEC3D602E5
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\peripheral\coretimer
  name: plib_coretimer.c
  physicalPath: peripheral\coretimer
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2FEFEA0D4E94F5A5F3D76BAEC3D602E5
- generatedChecksum: 84A02BDC4B7228AA0FCDC98B7C2A04A0
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\peripheral\ddr
  name: plib_ddr.c
  physicalPath: peripheral\ddr
  security: NON_SECURE
  type: SOURCE
  userChecksum: 84A02BDC4B7228AA0FCDC98B7C2A04A0
- generatedChecksum: 24F9820F94E0347AF9B29DB7664BDC37
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 24F9820F94E0347AF9B29DB7664BDC37
- generatedChecksum: 953D0BCD584CE6BAAF2E253DBA03E02E
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\gfx\driver\glcd
  name: plib_glcd.c
  physicalPath: gfx\driver\controller\glcd
  security: NON_SECURE
  type: SOURCE
  userChecksum: 953D0BCD584CE6BAAF2E253DBA03E02E
- generatedChecksum: 5221410C6D6712CEB933589032201622
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5221410C6D6712CEB933589032201622
- generatedChecksum: 08F858BC766BF9C7602A55E3538BFBD5
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\peripheral\i2c\master
  name: plib_i2c1_master.c
  physicalPath: peripheral\i2c\master
  security: NON_SECURE
  type: SOURCE
  userChecksum: 08F858BC766BF9C7602A55E3538BFBD5
- generatedChecksum: 00476FA3C353B9AB067B0EDF1DD27182
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\system\input
  name: sys_input.c
  physicalPath: system\input
  security: NON_SECURE
  type: SOURCE
  userChecksum: 00476FA3C353B9AB067B0EDF1DD27182
- generatedChecksum: 99F5C28835CA70CF308C005561EF92C6
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\system\input
  name: sys_input_listener.c
  physicalPath: system\input
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99F5C28835CA70CF308C005561EF92C6
- generatedChecksum: 640A4B35B8CDB53BD8EA5077D81386BE
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\system\int
  name: sys_int.c
  physicalPath: system\int\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 640A4B35B8CDB53BD8EA5077D81386BE
- generatedChecksum: 40A99C84F50EB7DFAA579B8675F140DD
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\system\time
  name: sys_time.c
  physicalPath: system\time\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 40A99C84F50EB7DFAA579B8675F140DD
- generatedChecksum: CA1C07364DF7044B8D36B16DC4FC1B23
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: CA1C07364DF7044B8D36B16DC4FC1B23
- generatedChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 16BE5CCEE5F9AF5909BF3F69B51C7D93
- generatedChecksum: null
  logicalPath: ''
  name: app_glcd.h
  physicalPath: ..\..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 61C968603B4BF599D47ABD843C9B0016
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: 61C968603B4BF599D47ABD843C9B0016
- generatedChecksum: F850EF7288AAC2585C05EA936DA4BD36
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: F850EF7288AAC2585C05EA936DA4BD36
- generatedChecksum: DD53E86EAEF092E3BFA559A1FC5929F6
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: DD53E86EAEF092E3BFA559A1FC5929F6
- generatedChecksum: 5D5C52527AB1435153DB9B50ADE6B79D
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D5C52527AB1435153DB9B50ADE6B79D
- generatedChecksum: 1D2094DFA60F847FFD4E8153B6E78027
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\driver
  name: driver.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: 1D2094DFA60F847FFD4E8153B6E78027
- generatedChecksum: CC7DFCC51CD25171A3E400E18969354F
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\driver
  name: driver_common.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: CC7DFCC51CD25171A3E400E18969354F
- generatedChecksum: 18074A2B7B626F870F441A20E188E911
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\gfx\driver\glcd
  name: drv_gfx_glcd.h
  physicalPath: gfx\driver\controller\glcd
  security: NON_SECURE
  type: HEADER
  userChecksum: 18074A2B7B626F870F441A20E188E911
- generatedChecksum: 3C6689B8800C6234028EC2FBE82E25CF
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\driver\i2c
  name: drv_i2c.h
  physicalPath: driver\i2c
  security: NON_SECURE
  type: HEADER
  userChecksum: 3C6689B8800C6234028EC2FBE82E25CF
- generatedChecksum: 260EF469FECCFEF9418D6268909EE2F8
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\driver\i2c
  name: drv_i2c_definitions.h
  physicalPath: driver\i2c
  security: NON_SECURE
  type: HEADER
  userChecksum: 260EF469FECCFEF9418D6268909EE2F8
- generatedChecksum: 96E55AC4B3153F31385A2A7066E9CCBB
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\driver\input
  name: drv_maxtouch.h
  physicalPath: driver\input
  security: NON_SECURE
  type: HEADER
  userChecksum: 96E55AC4B3153F31385A2A7066E9CCBB
- generatedChecksum: BC1B87C8218F3A54788D9E6D2BAF8D85
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\gfx\driver\glcd
  name: gfx_driver.h
  physicalPath: gfx\driver
  security: NON_SECURE
  type: HEADER
  userChecksum: BC1B87C8218F3A54788D9E6D2BAF8D85
- generatedChecksum: 81B5408E380DF8AB26691BD8B8CA40F1
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\gfx\driver\2dgpu
  name: libnano2d.h
  physicalPath: gfx\driver\processor\2dgpu
  security: NON_SECURE
  type: HEADER
  userChecksum: 81B5408E380DF8AB26691BD8B8CA40F1
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 0AC88C49E4585B606FD5AC6804F0C340
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 0AC88C49E4585B606FD5AC6804F0C340
- generatedChecksum: B358678B02AC7D3AD6CC80621ECC826D
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\osal
  name: osal_impl_basic.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: B358678B02AC7D3AD6CC80621ECC826D
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 49EF1C56EBDEE25C8E46F029F020AB21
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\peripheral\coretimer
  name: plib_coretimer.h
  physicalPath: peripheral\coretimer
  security: NON_SECURE
  type: HEADER
  userChecksum: 49EF1C56EBDEE25C8E46F029F020AB21
- generatedChecksum: 425F94C116C19A85F8848CD44D94A5B8
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\peripheral\ddr
  name: plib_ddr.h
  physicalPath: peripheral\ddr
  security: NON_SECURE
  type: HEADER
  userChecksum: 425F94C116C19A85F8848CD44D94A5B8
- generatedChecksum: 1CD4F98B014C4BDB5AEF0E8B17B0EA93
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 1CD4F98B014C4BDB5AEF0E8B17B0EA93
- generatedChecksum: 7F658185A682EEB3E20A713742107A1B
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\gfx\driver\glcd
  name: plib_glcd.h
  physicalPath: gfx\driver\controller\glcd
  security: NON_SECURE
  type: HEADER
  userChecksum: 7F658185A682EEB3E20A713742107A1B
- generatedChecksum: D90AA9A4ECB5D746F95D35634DE121DD
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: D90AA9A4ECB5D746F95D35634DE121DD
- generatedChecksum: 407D8CE5F0C091BCEBB78967FECBE53E
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\peripheral\i2c\master
  name: plib_i2c1_master.h
  physicalPath: peripheral\i2c\master
  security: NON_SECURE
  type: HEADER
  userChecksum: 407D8CE5F0C091BCEBB78967FECBE53E
- generatedChecksum: B963C6FE44292A1C4A14C3BA5BE95AEE
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\peripheral\i2c\master
  name: plib_i2c_master_common.h
  physicalPath: peripheral\i2c\master
  security: NON_SECURE
  type: HEADER
  userChecksum: B963C6FE44292A1C4A14C3BA5BE95AEE
- generatedChecksum: 6972608768DDBE6E37A2D81B83DF490B
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\system\debug
  name: sys_debug.h
  physicalPath: system\debug
  security: NON_SECURE
  type: HEADER
  userChecksum: 6972608768DDBE6E37A2D81B83DF490B
- generatedChecksum: D21A943666F73BB99268A0C55B0327FD
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\system\input
  name: sys_input.h
  physicalPath: system\input
  security: NON_SECURE
  type: HEADER
  userChecksum: D21A943666F73BB99268A0C55B0327FD
- generatedChecksum: 5499BE8EDFB7930D2460DE8BA8E8818B
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\system\input
  name: sys_input_gesture.h
  physicalPath: system\input
  security: NON_SECURE
  type: HEADER
  userChecksum: 5499BE8EDFB7930D2460DE8BA8E8818B
- generatedChecksum: A254F5CC3DD63C1432666958260CADAB
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\system\input
  name: sys_input_keyboard.h
  physicalPath: system\input
  security: NON_SECURE
  type: HEADER
  userChecksum: A254F5CC3DD63C1432666958260CADAB
- generatedChecksum: 00AAAE838D855B5A8C560B371C7D0363
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\system\input
  name: sys_input_listener.h
  physicalPath: system\input
  security: NON_SECURE
  type: HEADER
  userChecksum: 00AAAE838D855B5A8C560B371C7D0363
- generatedChecksum: 9B0AB7A5A79745BE5AEC37B9A14D7090
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\system\input
  name: sys_input_mouse.h
  physicalPath: system\input
  security: NON_SECURE
  type: HEADER
  userChecksum: 9B0AB7A5A79745BE5AEC37B9A14D7090
- generatedChecksum: 6012C94D59E0E69145C089AB1F736C28
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\system\input
  name: sys_input_touch.h
  physicalPath: system\input
  security: NON_SECURE
  type: HEADER
  userChecksum: 6012C94D59E0E69145C089AB1F736C28
- generatedChecksum: 47330C2D8F204B2B69F8A86240A564B6
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\system\int
  name: sys_int.h
  physicalPath: system\int
  security: NON_SECURE
  type: HEADER
  userChecksum: 47330C2D8F204B2B69F8A86240A564B6
- generatedChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\system\int
  name: sys_int_mapping.h
  physicalPath: system\int
  security: NON_SECURE
  type: HEADER
  userChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
- generatedChecksum: 466D676839280C0E7FC2CC6F78BA6EE9
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\system\time
  name: sys_time.h
  physicalPath: system\time
  security: NON_SECURE
  type: HEADER
  userChecksum: 466D676839280C0E7FC2CC6F78BA6EE9
- generatedChecksum: 82C87C4CF49EE4D859363C15E9073333
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\system\time
  name: sys_time_definitions.h
  physicalPath: system\time
  security: NON_SECURE
  type: HEADER
  userChecksum: 82C87C4CF49EE4D859363C15E9073333
- generatedChecksum: 62F39464265EC34979649F761FB4FE57
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\system\time
  name: sys_time_local.h
  physicalPath: system\time\src
  security: NON_SECURE
  type: HEADER
  userChecksum: 62F39464265EC34979649F761FB4FE57
- generatedChecksum: BE95B4F134C5C929787B9DA6FDBF3501
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\system
  name: system.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: BE95B4F134C5C929787B9DA6FDBF3501
- generatedChecksum: C3F5136D520DAC4416512EBFCCA023C3
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\system
  name: system_common.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: C3F5136D520DAC4416512EBFCCA023C3
- generatedChecksum: 1C75A8A6B60598A2FD0D533F57839B72
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk\system
  name: system_module.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: 1C75A8A6B60598A2FD0D533F57839B72
- generatedChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
- generatedChecksum: null
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 9343B384F47862DF56D0EB9CAEF4A460
  logicalPath: config\glcd_rgba8888_mxt_mzda_extddr_sk
  name: p32MZ2064DAA288.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 9343B384F47862DF56D0EB9CAEF4A460
format_version: v1.0
libraries:
- name: libnano2d.a
  path: gfx/driver/processor/2dgpu/lib
  security: NON_SECURE
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/glcd_rgba8888_mxt_mzda_extddr_sk;../src/packs/PIC32MZ2064DAA288_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '8192'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/glcd_rgba8888_mxt_mzda_extddr_sk;../src/packs/PIC32MZ2064DAA288_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
