files:
- generatedChecksum: null
  logicalPath: ''
  name: app_glcd.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 3BBD6EF8C254B1A1FEE1B18437A03203
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3BBD6EF8C254B1A1FEE1B18437A03203
- generatedChecksum: 67CF0A9816BAAD32AD2BCD7595D30D74
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\gfx\driver\glcd
  name: drv_gfx_glcd.c
  physicalPath: gfx\driver\controller\glcd
  security: NON_SECURE
  type: SOURCE
  userChecksum: 67CF0A9816BAAD32AD2BCD7595D30D74
- generatedChecksum: 13F062B063A4F4AE0B19CE872943995B
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\driver\i2c
  name: drv_i2c.c
  physicalPath: driver\i2c\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 13F062B063A4F4AE0B19CE872943995B
- generatedChecksum: 37780F17759DED907A0F36E28BFB3136
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\driver\i2c
  name: drv_i2c_local.h
  physicalPath: driver\i2c\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 37780F17759DED907A0F36E28BFB3136
- generatedChecksum: D60987ADDBC55D814DF1F8934395B71C
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\driver\input
  name: drv_maxtouch.c
  physicalPath: driver\input
  security: NON_SECURE
  type: SOURCE
  userChecksum: D60987ADDBC55D814DF1F8934395B71C
- generatedChecksum: D230A6B646D2E78CEAA6AA924E04FCA0
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: D230A6B646D2E78CEAA6AA924E04FCA0
- generatedChecksum: 36FA79243A4ABD63DAAEA023290EDE3B
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\gfx\driver\glcd
  name: gfx_driver.c
  physicalPath: gfx\driver
  security: NON_SECURE
  type: SOURCE
  userChecksum: 36FA79243A4ABD63DAAEA023290EDE3B
- generatedChecksum: DBF2F283C0E29EFB91B780F9AFE2EA50
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: DBF2F283C0E29EFB91B780F9AFE2EA50
- generatedChecksum: 08355AC58D002240DDF162C3B53C47B4
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 08355AC58D002240DDF162C3B53C47B4
- generatedChecksum: 9542827A9CCC1BBB58C8119CD906FB1E
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\gfx\driver\2dgpu
  name: libnano2d.c
  physicalPath: gfx\driver\processor\2dgpu
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9542827A9CCC1BBB58C8119CD906FB1E
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 8F9739C5D0D0813AB30AAD000A5CC9BC
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8F9739C5D0D0813AB30AAD000A5CC9BC
- generatedChecksum: 2FEFEA0D4E94F5A5F3D76BAEC3D602E5
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\peripheral\coretimer
  name: plib_coretimer.c
  physicalPath: peripheral\coretimer
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2FEFEA0D4E94F5A5F3D76BAEC3D602E5
- generatedChecksum: 84A02BDC4B7228AA0FCDC98B7C2A04A0
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\peripheral\ddr
  name: plib_ddr.c
  physicalPath: peripheral\ddr
  security: NON_SECURE
  type: SOURCE
  userChecksum: 84A02BDC4B7228AA0FCDC98B7C2A04A0
- generatedChecksum: 9329B61F09AB291FBE95CDF5340A8393
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9329B61F09AB291FBE95CDF5340A8393
- generatedChecksum: 953D0BCD584CE6BAAF2E253DBA03E02E
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\gfx\driver\glcd
  name: plib_glcd.c
  physicalPath: gfx\driver\controller\glcd
  security: NON_SECURE
  type: SOURCE
  userChecksum: 953D0BCD584CE6BAAF2E253DBA03E02E
- generatedChecksum: 4730BB53A4A3A4C54850548D2687A6D6
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4730BB53A4A3A4C54850548D2687A6D6
- generatedChecksum: 08F858BC766BF9C7602A55E3538BFBD5
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\peripheral\i2c\master
  name: plib_i2c1_master.c
  physicalPath: peripheral\i2c\master
  security: NON_SECURE
  type: SOURCE
  userChecksum: 08F858BC766BF9C7602A55E3538BFBD5
- generatedChecksum: 42F3A1D9D54BCC7C91AA8D6156BAD7D0
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\system\input
  name: sys_input.c
  physicalPath: system\input
  security: NON_SECURE
  type: SOURCE
  userChecksum: 42F3A1D9D54BCC7C91AA8D6156BAD7D0
- generatedChecksum: 99F5C28835CA70CF308C005561EF92C6
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\system\input
  name: sys_input_listener.c
  physicalPath: system\input
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99F5C28835CA70CF308C005561EF92C6
- generatedChecksum: C95CE0ABB86E6B11CF77E8891D294510
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\system\int
  name: sys_int.c
  physicalPath: system\int\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: C95CE0ABB86E6B11CF77E8891D294510
- generatedChecksum: 83BDE663A1AAB20C9E52263F22E2ED3C
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\system\time
  name: sys_time.c
  physicalPath: system\time\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 83BDE663A1AAB20C9E52263F22E2ED3C
- generatedChecksum: CA1C07364DF7044B8D36B16DC4FC1B23
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: CA1C07364DF7044B8D36B16DC4FC1B23
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: null
  logicalPath: ''
  name: app_glcd.h
  physicalPath: ..\..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: E440C64D7411EAEE7CAA3800EE9BBA18
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: E440C64D7411EAEE7CAA3800EE9BBA18
- generatedChecksum: F850EF7288AAC2585C05EA936DA4BD36
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: F850EF7288AAC2585C05EA936DA4BD36
- generatedChecksum: 27AD185CFD1B3E7E331A7F5248A3EE44
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 27AD185CFD1B3E7E331A7F5248A3EE44
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 1D2094DFA60F847FFD4E8153B6E78027
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\driver
  name: driver.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: 1D2094DFA60F847FFD4E8153B6E78027
- generatedChecksum: CC7DFCC51CD25171A3E400E18969354F
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\driver
  name: driver_common.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: CC7DFCC51CD25171A3E400E18969354F
- generatedChecksum: 18074A2B7B626F870F441A20E188E911
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\gfx\driver\glcd
  name: drv_gfx_glcd.h
  physicalPath: gfx\driver\controller\glcd
  security: NON_SECURE
  type: HEADER
  userChecksum: 18074A2B7B626F870F441A20E188E911
- generatedChecksum: 3C6689B8800C6234028EC2FBE82E25CF
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\driver\i2c
  name: drv_i2c.h
  physicalPath: driver\i2c
  security: NON_SECURE
  type: HEADER
  userChecksum: 3C6689B8800C6234028EC2FBE82E25CF
- generatedChecksum: 260EF469FECCFEF9418D6268909EE2F8
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\driver\i2c
  name: drv_i2c_definitions.h
  physicalPath: driver\i2c
  security: NON_SECURE
  type: HEADER
  userChecksum: 260EF469FECCFEF9418D6268909EE2F8
- generatedChecksum: 96E55AC4B3153F31385A2A7066E9CCBB
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\driver\input
  name: drv_maxtouch.h
  physicalPath: driver\input
  security: NON_SECURE
  type: HEADER
  userChecksum: 96E55AC4B3153F31385A2A7066E9CCBB
- generatedChecksum: D734853EAED28FB72CF8B3BD9029AABD
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\gfx\driver\glcd
  name: gfx_driver.h
  physicalPath: gfx\driver
  security: NON_SECURE
  type: HEADER
  userChecksum: D734853EAED28FB72CF8B3BD9029AABD
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 81B5408E380DF8AB26691BD8B8CA40F1
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\gfx\driver\2dgpu
  name: libnano2d.h
  physicalPath: gfx\driver\processor\2dgpu
  security: NON_SECURE
  type: HEADER
  userChecksum: 81B5408E380DF8AB26691BD8B8CA40F1
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 0AC88C49E4585B606FD5AC6804F0C340
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 0AC88C49E4585B606FD5AC6804F0C340
- generatedChecksum: B040122CCA94A0636810D6F15F13B751
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\osal
  name: osal_impl_basic.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: B040122CCA94A0636810D6F15F13B751
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 49EF1C56EBDEE25C8E46F029F020AB21
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\peripheral\coretimer
  name: plib_coretimer.h
  physicalPath: peripheral\coretimer
  security: NON_SECURE
  type: HEADER
  userChecksum: 49EF1C56EBDEE25C8E46F029F020AB21
- generatedChecksum: 87DC43CEB84F8AF12C9F67196470E23F
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\peripheral\ddr
  name: plib_ddr.h
  physicalPath: peripheral\ddr
  security: NON_SECURE
  type: HEADER
  userChecksum: 87DC43CEB84F8AF12C9F67196470E23F
- generatedChecksum: D1E6260A2C117FBD35FB8C9CCB5DFD2F
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: D1E6260A2C117FBD35FB8C9CCB5DFD2F
- generatedChecksum: 7F658185A682EEB3E20A713742107A1B
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\gfx\driver\glcd
  name: plib_glcd.h
  physicalPath: gfx\driver\controller\glcd
  security: NON_SECURE
  type: HEADER
  userChecksum: 7F658185A682EEB3E20A713742107A1B
- generatedChecksum: 59D5D7986F6DDEAAE368B21BDB7F7BD9
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 59D5D7986F6DDEAAE368B21BDB7F7BD9
- generatedChecksum: 407D8CE5F0C091BCEBB78967FECBE53E
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\peripheral\i2c\master
  name: plib_i2c1_master.h
  physicalPath: peripheral\i2c\master
  security: NON_SECURE
  type: HEADER
  userChecksum: 407D8CE5F0C091BCEBB78967FECBE53E
- generatedChecksum: B963C6FE44292A1C4A14C3BA5BE95AEE
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\peripheral\i2c\master
  name: plib_i2c_master_common.h
  physicalPath: peripheral\i2c\master
  security: NON_SECURE
  type: HEADER
  userChecksum: B963C6FE44292A1C4A14C3BA5BE95AEE
- generatedChecksum: 6972608768DDBE6E37A2D81B83DF490B
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\system\debug
  name: sys_debug.h
  physicalPath: system\debug
  security: NON_SECURE
  type: HEADER
  userChecksum: 6972608768DDBE6E37A2D81B83DF490B
- generatedChecksum: 533CEADA23BA3DB1FDC642E71682110D
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\system\input
  name: sys_input.h
  physicalPath: system\input
  security: NON_SECURE
  type: HEADER
  userChecksum: 533CEADA23BA3DB1FDC642E71682110D
- generatedChecksum: 326B45D18D7A6BB4B2D1E0FCF50EF176
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\system\input
  name: sys_input_gesture.h
  physicalPath: system\input
  security: NON_SECURE
  type: HEADER
  userChecksum: 326B45D18D7A6BB4B2D1E0FCF50EF176
- generatedChecksum: A254F5CC3DD63C1432666958260CADAB
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\system\input
  name: sys_input_keyboard.h
  physicalPath: system\input
  security: NON_SECURE
  type: HEADER
  userChecksum: A254F5CC3DD63C1432666958260CADAB
- generatedChecksum: 34162E1DCA132A3EAB3767F529CFD195
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\system\input
  name: sys_input_listener.h
  physicalPath: system\input
  security: NON_SECURE
  type: HEADER
  userChecksum: 34162E1DCA132A3EAB3767F529CFD195
- generatedChecksum: 9B0AB7A5A79745BE5AEC37B9A14D7090
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\system\input
  name: sys_input_mouse.h
  physicalPath: system\input
  security: NON_SECURE
  type: HEADER
  userChecksum: 9B0AB7A5A79745BE5AEC37B9A14D7090
- generatedChecksum: 6012C94D59E0E69145C089AB1F736C28
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\system\input
  name: sys_input_touch.h
  physicalPath: system\input
  security: NON_SECURE
  type: HEADER
  userChecksum: 6012C94D59E0E69145C089AB1F736C28
- generatedChecksum: 47330C2D8F204B2B69F8A86240A564B6
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\system\int
  name: sys_int.h
  physicalPath: system\int
  security: NON_SECURE
  type: HEADER
  userChecksum: 47330C2D8F204B2B69F8A86240A564B6
- generatedChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\system\int
  name: sys_int_mapping.h
  physicalPath: system\int
  security: NON_SECURE
  type: HEADER
  userChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
- generatedChecksum: 466D676839280C0E7FC2CC6F78BA6EE9
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\system\time
  name: sys_time.h
  physicalPath: system\time
  security: NON_SECURE
  type: HEADER
  userChecksum: 466D676839280C0E7FC2CC6F78BA6EE9
- generatedChecksum: 9463F9BBF69C9593FF3B30F8BC587234
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\system\time
  name: sys_time_definitions.h
  physicalPath: system\time
  security: NON_SECURE
  type: HEADER
  userChecksum: 9463F9BBF69C9593FF3B30F8BC587234
- generatedChecksum: 62F39464265EC34979649F761FB4FE57
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\system\time
  name: sys_time_local.h
  physicalPath: system\time\src
  security: NON_SECURE
  type: HEADER
  userChecksum: 62F39464265EC34979649F761FB4FE57
- generatedChecksum: BE95B4F134C5C929787B9DA6FDBF3501
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\system
  name: system.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: BE95B4F134C5C929787B9DA6FDBF3501
- generatedChecksum: C3F5136D520DAC4416512EBFCCA023C3
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\system
  name: system_common.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: C3F5136D520DAC4416512EBFCCA023C3
- generatedChecksum: 1C75A8A6B60598A2FD0D533F57839B72
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk\system
  name: system_module.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: 1C75A8A6B60598A2FD0D533F57839B72
- generatedChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
- generatedChecksum: null
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 8EAA511DA1FA9BAB44A936B76259BFE9
  logicalPath: config\glcd_rgba8888_mxt_mzda_intddr_sk
  name: p32MZ2064DAR169.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 8EAA511DA1FA9BAB44A936B76259BFE9
format_version: v1.0
libraries:
- name: libnano2d.a
  path: gfx/driver/processor/2dgpu/lib
  security: NON_SECURE
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/glcd_rgba8888_mxt_mzda_intddr_sk;../src/packs/PIC32MZ2064DAR169_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '8192'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/glcd_rgba8888_mxt_mzda_intddr_sk;../src/packs/PIC32MZ2064DAR169_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
