format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_PIC32MZ_DA_Radial_Board, bsp: 'true'}
children:
- type: ElementPosition
  attributes: {x: '54', y: '269', id: BSP_PIC32MZ_DA_Radial_Board}
