format_version: v1.0
type: UniqueComponent
attributes: {id: le_gfx_driver_glcd}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: DisplayHeight}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_glcd, value: '272'}
  - type: Integer
    attributes: {id: DisplayWidth}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_glcd, value: '480'}
  - type: Integer
    attributes: {id: PixelClock}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_glcd, value: '16666666'}
  - type: Integer
    attributes: {id: PixelClockDivider}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '12'}
  - type: Integer
    attributes: {id: TotalNumLayers}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: le_gfx_driver_glcd, value: '3'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: Graphics Display}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: gfx_disp_pdatm4301b_480x272}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: gfx_display}
- type: ElementPosition
  attributes: {x: '378', y: '79', id: le_gfx_driver_glcd}
