configName: glcd_rgba8888_mxt_mzda_intddr_cu_wqvga
folderName: ''
format_version: v1.0
frameworkPath: ../../../../../H3
processor: PIC32MZ2064DAR176
projectName: ''
settings:
  PackageFilter: aerospace;audio;bsp;core;csp;gfx;gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;touch;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: OVERWRITE
  DFPPath: .\dev_packs\Microchip\PIC32MZ-DA_DFP\1.3.111\atdf\PIC32MZ2064DAR176.atdf
