configName: glcd_rgba8888_mxt_mzda_intddr_cu
folderName: legato_qs_x_r_fs_mzef_cu_tm4301b
format_version: v1.0
frameworkPath: ..\..\..\..\harmony3_dev
processor: PIC32MZ2064DAR176
projectName: legato_qs_x_r_fs_mzef_cu_wqvga
settings:
  PackageFilter: aerospace;audio;bsp;core;csp;gfx;harmony_gfx_apps_pic32mz_da;harmony_gfx_apps_pic32mz_ef;harmony_gfx_apps_sam_9x60;harmony_gfx_apps_sam_a5d2;harmony_gfx_apps_sam_c20_c21;harmony_gfx_apps_sam_d5x_e5x;harmony_gfx_apps_sam_e70_s70_v70_v71;touch;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-DA_DFP\1.4.118\atdf\PIC32MZ2064DAR176.atdf
