format_version: v1.0
type: UniqueComponent
attributes: {id: tmr1}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: TIMER1_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr1, value: '100000000'}
  - type: Long
    attributes: {id: TIMER1_PERIOD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr1, value: '29999'}
  - type: Comment
    attributes: {id: TMR1_INTRRUPT_ENABLE_COMMENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
- type: ElementPosition
  attributes: {x: '149', y: '424', id: tmr1}
