configName: glcd_rgba8888_mxt_mzda_intddr_sk
folderName: legato_qs_x_r_usb_fs_mzda_intddr_sk_meb2_tm4301b
format_version: v1.0
frameworkPath: ..\..\..\..\harmony3_dev
processor: PIC32MZ2064DAS169
projectName: legato_qs_x_r_usb_fs_mzda_intddr_sk_meb2_wqvga
settings:
  PackageFilter: bsp;core;csp;gfx;quick_docs;touch;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-DA_DFP\1.3.111\atdf\PIC32MZ2064DAS169.atdf
