configName: glcd_rgba8888_mxt_mzda_intddr_sk
folderName: legato_qs_x_r_usb_fs_mzda_intddr_sk_meb2_tm4301b
format_version: v1.0
frameworkPath: ..\..\..\..\harmony3_dev
processor: PIC32MZ2064DAS169
projectName: legato_qs_x_r_usb_fs_mzda_intddr_sk_meb2_wqvga
settings:
  PackageFilter: audio;azure_rtos;bootloader;bootloader_apps_can;bootloader_apps_i2c;bootloader_apps_uart;bsp;core;core_apps_pic32mx;core_apps_pic32mz_da;core_apps_pic32mz_ef;crypto;cryptoauthlib;csp;csp_apps_pic32mk;csp_apps_pic32mx;csp_apps_pic32mz_da;csp_apps_pic32mz_ef;csp_apps_sam_c20_c21;csp_apps_sam_d5x_e5x;csp_apps_sam_e70_s70_v70_v71;dev_packs;gfx;gfx_apps;gfx_apps_pic32mz_da;gfx_apps_pic32mz_ef;gfx_apps_sam_9x60;gfx_apps_sam_a5d2;gfx_apps_sam_c20_c21;gfx_apps_sam_d5x_e5x;gfx_apps_sam_e70_s70_v70_v71;gfx_old;harmony-services;net;net_apps_sam_e70_v71;quick_docs;touch;usb;wireless;wireless_wifi
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-DA_DFP\1.4.118\atdf\PIC32MZ2064DAS169.atdf
