configName: glcd_rgba8888_mxt_mzda_intddr_cu_90
folderName: legato_qs_mzda_cu_tm4301b_90
format_version: v1.0
frameworkPath: ..\..\..
processor: PIC32MZ2064DAR176
projectName: glcd_rgba8888_mxt_mzda_intddr_cu_90
settings:
  PackageFilter: audio;bsp;bt;core;csp;csp_apps_sam_9x60;gfx;aerospace;gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;gfx_apps_pic32mz_da;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-DA_DFP\1.4.118\atdf\PIC32MZ2064DAR176.atdf
